name: Build and deploy Angular application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v2
        with:
          ref: TP-Final-HIA

      - name: Build application
        run: |
          ng build --prod

      - name: Check for changes
        run: |
          docker-compose config | diff -u docker-compose.orig

      - name: Deploy web container
        run: |
          if [ "$?" -ne 0 ]; then
          cd ./proyecto-final-backend/web && docker-compose up -d --no-deps --build web
          fi

      - name: Check container logs
        run: |
          docker-compose logs -f web
