version: '3'

networks:
  tpfinal:
    driver: bridge

services:

  nodejs:
    container_name: nodejs
    restart: always
    build: .
    ports:
      - "3000:3000"
    networks:
      - tpfinal
    links:
      - mongo
      - web

  mongo:
    container_name: mongobd
    image: mongo
    ports:
      - "27018:27017"
    networks:
      - tpfinal

  web:
    container_name: web
    image: alexmamani/frontend:1.2
    ports:
      - "8090:80"
    networks:
      - tpfinal
    dns:
      - 8.8.8.8
      - 8.8.4.4

  dns:
    container_name: dnsmasq
    image: andyshinn/dnsmasq
    restart: always
    networks:
      - tpfinal

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - tpfinal
    environment:
      - WATCHTOWER_POLL_INTERVAL=300
      - WATCHTOWER_MONITOR_ONLY=false
      - WATCHTOWER_CLEANUP=false
