name: Build and deploy Angular application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v2
        with:
          ref: TP-Final-HIA

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y libffi-dev libssl-dev openssl

      - name: Build application
        run: |
          ng build --prod

      - name: Build web container
        run: |
          docker-compose build web

      - name: Deploy web container
        run: |
          docker-compose up -d web
