name: Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        run: docker-compose build web

      - name: Up Docker container
        run: docker-compose up -d --no-deps --build web
