name: Docker Compose

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker-compose -f proyecto-final-backend/web/docker-compose.yml build web

      - name: Up Docker container
        run: |
          docker-compose -f proyecto-final-backend/web/docker-compose.yml up -d
